  - name: install packaches all-nodes
    yum:
      name:
        - epel-release
        - sshpass
        - tree
        - dnf
        - chrony
        - mlocate
        - sshpass
      state: present
      update_cache: true

  - name: update packages
    yum:
      name:
        - systemd
      state: latest


  - name: enabling services
    service: 
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - tuned
      - chronyd
 