  - name: enable ssh pwd login
    replace:
      dest: "/etc/ssh/sshd_config"
      regexp: 'PasswordAuthentication no'
      replace: 'PasswordAuthentication yes'
    tags: ssh
   
  - name:  restart sshd
    service:
      name:  sshd
      state: restarted
    tags: ssh

  - name: install packages all-nodes
    yum:
      name:
        - epel-release
        - sshpass
        - tree
        - dnf
        - chrony
        - mlocate
        - sshpass
        - python3-pip
        - audispd-plugins
        - rsyslog
      state: present
      update_cache: true
  
  - name: update packages
    yum:
      name:
        - systemd
      state: latest

  - name: install zabbix-apiexit
    shell: python3 -m pip install zabbix-api
    # pip:
    #   executable: pip3.3
    #   requirements: community.zabbix/requirements.txt
    # #state: latest
    tags: py

  - name: Set timezone
    timezone:
      name: Europe/Moscow

  - name: enabling services
    service: 
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - chronyd
      - rsyslog
 

  - name: set zabbix.example.com in hosts
    lineinfile:
      dest: /etc/hosts
      line: 10.10.20.50 zabbix.example.com
      state: present
    tags: hostname


  - shell: updatedb