# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

	config.vm.define "host1" do |host1|

	 host1.vm.box = "centos/8"
	
    host1.vm.network :private_network, ip: "10.0.0.100"
    


end


	config.vm.define "host2" do |host2|

	 host2.vm.box = "centos/8"
	
    host2.vm.network :private_network, ip: "10.0.0.101"
    end







 # config.ssh.username = 'vagrant'
 # config.ssh.password = 'vagrant'
  #config.ssh.insert_key = false


config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
     systemctl restart sshd.service


sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
  SHELL




end
