---
- hosts: all  
  become: yes
  tasks: 
    - name: install epel
      yum:
        name: epel-release
        state: present
    - name: ins borg
      yum:
        name: openvpn, easy-rsa
        state: present



      
  become: yes


