---
# tasks file for backup for all servers where backup
  - name: ins borg
    yum:
      name: 
        - borgbackup
      state: present
      
  - name: enable powertools
    shell: yum config-manager --set-enabled powertools
    when: ansible_hostname == 'monitoring'

  - name: creating ssh-keys for root
    user: 
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 2048
      

  - name: creating backup user
    user: 
      name: borg
      password: "{{ borg_pass | password_hash('sha512')}}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      group: wheel
        

  - name: disable host key checking
    replace:
      dest: "/etc/ssh/ssh_config"
      regexp: '#   StrictHostKeyChecking ask'
      replace: 'StrictHostKeyChecking no'
    notify: restart sshd

  - name: ssh-copy-id to backup server {{ backup_server }}
    shell: "sshpass -p {{ borg_pass }} ssh-copy-id borg@{{ backup_server }}"
    become: yes
    tags: copyid

  - name: copy env file of borg
    template:
      src: .env.j2
      dest: /home/borg/.env
      # owner: borg
      # group: borg
      mode: 0644

  - name: config backup server
    include: backup.yml
    when: (ansible_hostname == 'backup')
    
  - name: init repo if exists skip
    shell: source /home/borg/.env; borg init --encryption repokey $BORG_REPO/$(hostname) || /bin/true;
    become: yes
    register: result
    tags: init, backup

  - name: create service if needed
    include: create_borg_service.yml
    when: create_service == true
    tags: bak_service

#  - debug: msg={{bak_dir}}
#    tags: debuk