# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
	
    config.vm.network :private_network, ip: "10.0.0.100"
   # config.vm.provider :virtualbox do |vb|
    #  vb.memory = "1024"
     # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  #  end





  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "playbook.yml"
  
  end



#config.vm.provision "shell",
 #   name: "configuration",
  #  path: "init.sh"




end
