
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 2
end

config.vm.define "router1" do |router|
	router.vm.network "private_network", ip: "192.168.12.10", netmask: "255.255.255.0", adapter: 2, virtualbox__intnet:'r1-r2'
	router.vm.network "private_network", ip: "192.168.13.10", netmask: "255.255.255.0", adapter: 3, virtualbox__intnet:'r1-r3'
	router.vm.network "private_network", ip: "192.168.110.10", netmask: "255.255.255.0", adapter: 4, virtualbox__intnet:'net1'
	router.vm.network "private_network", ip: "192.168.50.11", adapter: 5
	router.vm.hostname = "router1"
end

config.vm.define "router2" do |router|
	router.vm.network "private_network", ip: "192.168.12.20", netmask: "255.255.255.0", adapter: 2, virtualbox__intnet:'r1-r2'
	router.vm.network "private_network", ip: "192.168.23.20", netmask: "255.255.255.0", adapter: 3, virtualbox__intnet:'r2-r3'
	router.vm.network "private_network", ip: "192.168.120.10", netmask: "255.255.255.0", adapter: 4, virtualbox__intnet:'net2'
	router.vm.network "private_network", ip: "192.168.50.12", adapter: 5
	router.vm.hostname = "router2"
end

config.vm.define "router3" do |router|
	router.vm.network "private_network", ip: "192.168.23.30", netmask: "255.255.255.0", adapter: 2, virtualbox__intnet:'r2-r3'
	router.vm.network "private_network", ip: "192.168.13.30", netmask: "255.255.255.0", adapter: 3, virtualbox__intnet:'r1-r3'
	router.vm.network "private_network", ip: "192.168.130.10", netmask: "255.255.255.0", adapter: 4, virtualbox__intnet:'net3'
	router.vm.network "private_network", ip: "192.168.50.13", adapter: 5
	router.vm.hostname = "router3"

	router.vm.provision "ansible" do |ansible|
		ansible.playbook = "ansible/provision.yml"
		ansible.inventory_path = "ansible/hosts"
		ansible.host_key_checking = "false"
		ansible.limit = "all"
	end
end

end


