
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "router1" do |router|
        router.vm.network "private_network", ip: '10.0.10.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1-r2"
        router.vm.network "private_network", ip: '10.0.12.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1-r3"
        router.vm.network "private_network", ip: '192.168.10.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net1"
        router.vm.network "private_network", ip: '192.168.50.11', adapter: 5
    router.vm.hostname = "router1"
    end

    config.vm.define "router2" do |router|
        router.vm.network "private_network",ip: '10.0.10.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1-r2"
        router.vm.network "private_network",ip: '10.0.11.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r2-r3"
        router.vm.network "private_network",ip: '192.168.20.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net2"
        router.vm.network "private_network",ip: '192.168.50.12', adapter: 5
    router.vm.hostname = "router2"
    end

    config.vm.define "router3" do |router|
        router.vm.network "private_network",ip: '10.0.11.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r2-r3"
        router.vm.network "private_network",ip: '10.0.12.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1-r3"
        router.vm.network "private_network",ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net3"
        router.vm.network "private_network",ip: '192.168.50.13', adapter: 5
    router.vm.hostname = "router3"

    router.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/provision.yml"
                ansible.inventory_path = "ansible/hosts"
                ansible.host_key_checking = "false"
                ansible.limit = "all"
        end
    end

end


