
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define "inetRouter" do |vm|
      vm.vm.network "private_network", adapter: 2, virtualbox__intnet: "router-net",  auto_config: "false", ip: "10.10.20.254"
      vm.vm.network "private_network", adapter: 3, virtualbox__intnet: "router-net",  auto_config: "false", ip: "10.10.20.253"
      vm.vm.network "private_network", ip: "192.168.50.10", adapter: 5   
      vm.vm.hostname = "inetRouter"
    end


    config.vm.define "centralRouter" do |vm|
      vm.vm.network "private_network", adapter: 2, virtualbox__intnet: "router-net",  auto_config: "false", ip: "10.10.20.252"
      vm.vm.network "private_network", adapter: 3, virtualbox__intnet: "router-net",  auto_config: "false", ip: "10.10.20.251"
      vm.vm.network "private_network", adapter: 4, virtualbox__intnet: "test-net"        ,  auto_config: "false", ip: "10.10.11.254"
      vm.vm.network "private_network", ip: "192.168.50.20", adapter: 5
      vm.vm.hostname = "centralRouter"
    end

    
    config.vm.define "testClient1" do |vm|
      vm.vm.network "private_network", adapter: 4, virtualbox__intnet: "test-net"    ,  auto_config: "false", ip: "10.10.11.251"
      vm.vm.network "private_network", ip: "192.168.50.30", adapter: 5
      vm.vm.hostname = "testClient1"
    end

    
    config.vm.define "testClient2" do |vm|
      vm.vm.network "private_network", adapter: 4, virtualbox__intnet: "test-net"           ,  auto_config: "false", ip: "10.10.11.252"
      vm.vm.network "private_network", ip: "192.168.50.40", adapter: 5
      vm.vm.hostname = "testClient2"
    end

    
    config.vm.define "testServer1" do |vm|
      vm.vm.network "private_network", adapter: 4, virtualbox__intnet: "test-net"    ,  auto_config: "false", ip: "10.10.11.253"
      vm.vm.network "private_network", ip: "192.168.50.50", adapter: 5
      vm.vm.hostname = "testServer1"
    end

    
    config.vm.define "testServer2" do |vm|
      vm.vm.network "private_network", adapter: 4, virtualbox__intnet: "test-net"    ,  auto_config: "false", ip: "10.10.11.254"
      vm.vm.network "private_network", ip: "192.168.50.60", adapter: 5
      vm.vm.hostname = "testServer2"
    end


    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "inventory/hosts"
      ansible.config_file = "ansible.cfg"
      ansible.host_key_checking = "false"
      #ansible.limit = "all"
      #ansible.tags = "slave"
      #ansible.verbose = "-vvv"
    end 
  
end


