Vagrant.configure(2) do |config|
        config.vm.box = "bento/centos-8.4"

  config.vm.provider "virtualbox" do |v|
        v.memory = 1024
  v.cpus = 2
  end


  config.vm.define "pxeserver" do |pxeserver|

    pxeserver.vm.network "private_network", ip: "192.168.51.10"
    pxeserver.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet:'pxenet'
	pxeserver.vm.provision "ansible" do |ansible|
                        ansible.playbook =  "provision.yml"
			ansible.inventory_path = "hosts"
                end
	

  end


        config.vm.define "pxeclient" do |pxeclient|
                pxeclient.vm.network "private_network", ip: "192.168.50.20"
		pxeclient.vm.provider :virtualbox do |vb|


 vb.customize [
          'modifyvm', :id,
          '--nic1', 'intnet',
          '--intnet1', 'pxenet',
          '--nic2', 'nat',
          '--boot1', 'net',
          '--boot2', 'none',
          '--boot3', 'none',
          '--boot4', 'none'
        ]


		end

  end
end
