all:
  hosts:
    gentoo1:
      ansible_host: 192.168.50.10
      osd_host: "10.10.20.10/24"
      # if defined will create conf
      osd_mac: '86:e6:0f:9d:5d:69'
      mon_mac: #"02:a7:dc:9b:1b:4a"
    gentoo2:
      ansible_host: 192.168.50.20
      osd_host: "10.10.20.20/24"
      mon_mac: #"02:a7:dc:9b:1b:4a"
    gentoo3:
      ansible_host: 192.168.50.30
      osd_host: "10.10.20.30/24"
      mon_mac: #"02:a7:dc:9b:1b:4a"

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  # management if name
    mgmt: "mgmt"
    dns: "1.1.1.1"
    def_gw: "10.0.11.1"
  # add if names
    eth1: eth0
    eth2: eth1
  # name for ovs br name
    osd_name: osd
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
