Vagrant.configure("2") do |config|
    config.vm.box = "generic/gentoo"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end


    (1..3).each do |i|
      config.vm.define "gentoo#{i}" do |gentoo|
        gentoo.vm.network "private_network", adapter: 2, virtualbox__intnet: "gentoo-net",  ip: "10.10.20.#{$i}0"
        gentoo.vm.network "private_network", adapter: 5, ip: "192.168.50.#{i}0"
        gentoo.vm.hostname = "gentoo#{i}"
      end
    end



  #    config.vm.provision "ansible" do |ansible|
  #    ansible.playbook = "setup.yml"
  #    ansible.inventory_path = "inventory"
  #    ansible.config_file = "ansible.cfg"
  #    ansible.host_key_checking = "false"
  #    ansible.limit = "all"    
  #  end 
  

end

