---
- name: all_host_provision
  gather_facts: true
  hosts: all
  become: true
  tasks:
      - name: install soft
        yum:
          name: epel-release, mtr, nmap, tcpdump
          state: present
          update_cache: true
     
      - name: ipv4 forward
        sysctl:
          name: net.ipv4.conf.all.forwarding 
          value: '1'
          sysctl_set: yes
 
      - name: restart fw
        service:
          name: firewalld
          enabled: yes
          state: started
        when: "'routers' in group_names"
      - name: Copy knock sh config to centralRouter
        template:
          src: conf/knock.sh
          dest: /opt/knock.sh
        when: (ansible_hostname == "centralRouter")

# dst-nat


- name: inetRouter
  gather_facts: true
  hosts: inetRouter
  become: true
  tasks:
    
      - name: masquerade_conf
        firewalld:
          masquerade: yes
          state: enabled
          permanent: yes
          immediate: yes
        
    
        
      - name: install soft for knock
        yum:
          name: knock-server
          state: present
          update_cache: true
 
      - name: add knockd interface conf
        lineinfile:
          path: /etc/sysconfig/knockd
          line: OPTIONS="-i eth1"
          state: present

      - name: Copy knockd config to inetRouter
        template:
          src: conf/knockd.conf
          dest: /etc/knockd.conf
          owner: root
          group: root
          mode: 060
      
      - name: start knockd
        service:
          name: knockd
          enabled: yes
          state: started





- name: inetRouter2
  gather_facts: true
  hosts: inetRouter2
  become: true
  tasks:

      - name: route add
        nmcli:
          conn_name: "System eth1"
          type: ethernet
          ifname: eth2
          gw4: '192.168.50.10'
          ip4: '192.168.50.11/24'
          autoconnect: yes
          state: present
      
      - name: disable def route
        shell: ip r del default via 10.0.2.2 || /bin/true

      - name: restart NM conn
        shell: nmcli c down System\ eth1 && nmcli c up System\ eth1

      - name: dst-nat
        firewalld:
          rich_rule: 'rule family=ipv4 forward-port port=8080 protocol=tcp to-port=80 to-addr=192.168.50.13'
          permanent: yes
          state: enabled
          immediate: yes

    
      - name: masquerade_conf
        firewalld:
          masquerade: yes
          state: enabled
          permanent: yes
          immediate: yes

- name: centralServer
  gather_facts: true
  hosts: centralServer
  become: true
  tasks:

      - name: route add
        nmcli:
          conn_name: "System eth1"
          type: ethernet
          ifname: eth1
          gw4: '192.168.50.10'
          ip4: '192.168.50.13/24'
          autoconnect: yes
          state: present

      
      - name: disable def route
        shell: ip r del default via 10.0.2.2 || /bin/true

      - name: restart NM conn
        shell: nmcli c down System\ eth1 && nmcli c up System\ eth1

      - name: install nginx
        yum:
          name: nginx
          state: present
  #        update_cache: true
      
      - name: restart nginx
        service:
          name: nginx
          enabled: yes
          state: started




