MACHINES = {
  :inetRouter => {
        :box_name => "centos/7",
        :vm_name => "inetRouter",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.50.10', adapter: 8},
                ]
  },
  :inetRouter2 => {
        :box_name => "centos/7",
        :vm_name => "inetRouter2",
        :net => [
  #                 {ip: '192.168.255.2', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "centralNet"},
                   {ip: '192.168.50.11', adapter: 8},
                ]  
  },
  :centralRouter => {
        :box_name => "centos/7",
        :vm_name => "centralRouter",
        :net => [
 #                  {ip: '192.168.255.3', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "centralNet"},
                   {ip: '192.168.50.12', adapter: 8},
                ]
  },
  :centralServer => {
        :box_name => "centos/7",
        :vm_name => "centralServer",
        :net => [
#                   {ip: '192.168.255.13', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "centralNet"},
                   {ip: '192.168.50.13', adapter: 8},


                ]
  },
  
  

}



Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
        v.memory = 512
  v.cpus = 1
  end


  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

#        if boxconfig.key?(:public)
 #         box.vm.network "public_network", boxconfig[:public]
  #      end


               box.vm.provision "ansible" do |ansible|
                        ansible.playbook =  "provision.yml"
                       ansible.inventory_path = "hosts"
                end
       end
  end
end

