---
# tasks file for gateway
  - name: install epel
    yum:
      name:
        - epel-release
      state: present
      update_cache: true

  - name: install soft
    yum:
      name: 
        - vim
        - mtr
        - tcpdump
        - net-tools
        - nginx
      state: present
      update_cache: true

  - name: set up forward 
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

  - name: copy nginx conf
    template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      
  - name: enabling services 
    service:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    with_items: 
      - firewalld
      - nginx

  - name: enabling masquerade
    firewalld:
      masquerade: yes
      state: enabled
      permanent: yes
      immediate: yes

  - name: enabling http
    firewalld:
      service: http
      state: enabled
      permanent: yes
      immediate: yes  
    tags: fw
    
  - name: enabling https
    firewalld:
      service: https
      state: enabled
      permanent: yes
      immediate: yes 
    tags: fw 




  # - name: dst-nat ssl to wordpress
  #   firewalld:
  #     rich_rule: 'rule family=ipv4 forward-port port=443 protocol=tcp to-port=443 to-addr=192.168.50.20'
  #     permanent: yes
  #     state: enabled
  #     immediate: yes
