---
# tasks file for gateway
  - name: install epel
    yum:
      name:
        - epel-release
      state: present
      update_cache: true

  - name: install soft
    yum:
      name: 
        - vim
        - mtr
        - tcpdump
        - net-tools
      state: present
      update_cache: true

  - name: set up forward 
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

  - name: enabling firewall 
    service:
      name: firewalld
      enabled: yes
      state: started

  - name: enabling masquerade
    firewalld:
      masquerade: yes
      state: enabled
      permanent: yes
      immediate: yes
    
  - name: dst-nat ssl to wordpress
    firewalld:
      rich_rule: 'rule family=ipv4 forward-port port=443 protocol=tcp to-port=443 to-addr=192.168.50.20'
      permanent: yes
      state: enabled
      immediate: yes
