# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.box = "centos/7"
 #config.vm.box_version = "2004.01"





# Base VM OS configuration.
# config.vm.box = "centos/7"

 config.vm.provider :virtualbox do |v|
 v.memory = 1024
 v.cpus = 2
 end

# a# Define two VMs with static private IP addresses.
 boxes = [
 { :name => "log",
 :ip => "192.168.51.15",
 },
 { :name => "web",
 :ip => "192.168.51.10",
 }
 ]
# # Provision each of the VMs.
 boxes.each do |opts|
 config.vm.define opts[:name] do |config|
 config.vm.hostname = opts[:name]
 config.vm.network "private_network", ip: opts[:ip]
 end
 end





  config.vm.provision "ansible" do |ansible|
  ansible.playbook = "playbook.yml"
  


config.vm.define "log" do |log|
  log.vm.provision "shell",
    name: "configuration",
    path: "init.sh"
  end

  config.vm.define "web" do |web|
  web.vm.provision "shell",
    name: "configuration",
    path: "init-web.sh"
  end




#config.vm.provision "shell",
 #   name: "configuration",
  #  path: "init.sh"

  end



end
