  - name: create xtrabackupservice
    template:
      src: xtrabackup.service.j2
      dest: /etc/systemd/system/xtrabackup.service

  - name: create xtrabackupservice timer
    template:
      src: xtrabackup.timer.j2
      dest: /etc/systemd/system/xtrabackup.timer

  - shell: systemctl daemon-reload
  - name: enable xtrabackupservice
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - xtrabackup.service
      - xtrabackup.timer
      
      