---
# tasks file for mysql
  - name: install percona remote rpm
    yum:
      name: "{{ perc_repo }}"
      state: present

  - name: enable percona repo ps80
    shell: "percona-release setup ps80 -y || /bin/true"

  - name: install packages
    yum: 
      name: 
        - epel-release
        - "{{ perc_srv }}"
        - dnf
        - percona-xtrabackup-80
        - nginx
      state: present
    tags: soft


  - name: install mysql_module_py
    dnf:
      name: python2-PyMySQL
      state: present

   
  - name: copy base-conf
    template:
      src: templates/01-base.cnf.j2
      dest: /etc/my.cnf.d/01-base.cnf
      owner: "mysql"
      mode: 0655
      force: yes

  - name: copy mysql conf
    copy:
      src: "{{ item }}"
      dest: "/etc/my.cnf.d/"
      owner: "mysql"
      mode: 0655
    with_fileglob:
      - "conf/conf.d/*"

  - name: Ensure MySQL is up-and-running
    service:
      name: mysql
      state: restarted
      enabled: yes
    tags: mysql
    # setpwd once
  - name: set pwd from temp
    shell: cat /var/log/mysqld.log | grep "temporary password" | grep -oE '[^ ]+$'
    register: tmp_root_password
    tags: 
      - mysql
      - setpwd

  - name: Set new password from temporary password ignoring errors
    shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_pass }}'');" --connect-expired-password -uroot -p"{{ tmp_root_password.stdout }}" || /bin/true'
    tags: 
      - mysql
      - setpwd

  - name: copy login/pwd
    copy:
      src: "templates/.my.cnf"
      dest: "/root/.my.cnf"
      owner: root
    tags: login

  - name: first start MySQL is up-and-running
    service:
      name: mysql
      state: started
      enabled: yes
    tags: mysql

  - name: set global gtid = on
    community.mysql.mysql_query:
      query: "{{ item }}"
      login_user: root
      login_unix_socket: "/var/lib/mysql/mysql.sock"
    with_items: 
      - "SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON;"
      - "SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE;"
      - "SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE;"
      - "SET @@GLOBAL.GTID_MODE = ON;"  
    tags: gtid

  - name: include master conf
    include: master.yml
    tags: master
    when: "ansible_hostname == 'mysql'"
 
  - name: include slave conf
    include: slave.yml
    tags: slave
    when: (replication_enabled == true) and ( ansible_hostname == 'mysqlslave' )

  - name: basic_full_backup
    include: mysql_bak.yml
    tags: bak