version: '3.3'
services:
  wordpress:
    image: wordpress:6.0.0-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER_NAME}"
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DB_HOST: "${DB_HOST}"
    volumes:
      - /home/vagrant/wordpress:/var/www/html:z
      - /var/log/nginx:/var/log/nginx:z
    networks:
      - app-network


  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/vagrant/wordpress:/var/www/html:z
      - /home/vagrant/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:z
      - /home/vagrant/nginx-conf/ssl:/etc/nginx/ssl:z
    networks:
      - app-network
    depends_on:
      - wordpress

networks:
  app-network:
    driver: bridge
