---
- name: monitoring
  hosts: monitoring
  gather_facts: true
  become: true
  tasks:

  - name: Create discovery rule with ICMP and zabbix agent checks
    community.zabbix.zabbix_discovery_rule:
      server_url: "http://zabbix.example.com/zabbix/"
      login_user: Admin
      login_password: zabbix
      name: local
      state: present
      iprange: 10.10.20.1-100
      dchecks:
          - type: ICMP
          - type: Zabbix
            key: "system.hostname"
            ports: 10050
            uniq: yes
            host_source: "discovery"
