---
- name: configure logserver
  hosts: logserver
  gather_facts: true
  become: true
  roles: 
    - collect-logs




- name: configure clients
  hosts: all, !logserver
  gather_facts: true
  become: true
  tasks:  
  
  - name: setup clients 
    yum:
      name:
        - rsyslog
      state: present
    tags: clients

  - name: setup client confs all
    template:
      src: group_vars/all.conf.j2
      dest: /etc/rsyslog.d/all.conf
    tags: clients

  - name: setup nginx confs 
    template:
      src: group_vars/local.nginx.conf.j2
      dest: /etc/rsyslog.d/nginx.conf
    tags: clients
    when: ansible_hostname == 'inetRouter' or ansible_hostname == 'wordpress'

  - name: insert imfile moudle line to rsyslog conf
    lineinfile:
      path: /etc/rsyslog.conf
      insertbefore: '$IncludeConfig /etc/rsyslog.d/*.conf'
      line: '$ModLoad imfile'


  - name: start rsyslog clients
    service: 
      name: rsyslog
      state: restarted
      enabled: yes
    tags: clients

  - name: reboot clients
    shell: reboot
    when: reboot_after_all == 'true'


