---
- name: monitoring
  hosts: monitoring
  gather_facts: true
  become: true
  roles: 
    - monitoring
    - community.zabbix/roles/zabbix_server/
  tags: srv


- name: monitoring
  hosts: monitoring
  gather_facts: true
  become: true
  roles: 
    - community.zabbix/roles/zabbix_web/
  tags: webs

- name: agent installation
  hosts: all
  gather_facts: true
  become: true
  roles: 
    - community.zabbix/roles/zabbix_agent/
  tags: agent