# ---
# - name: project
#   hosts: all
#   gather_facts: true
#   become: true
#   roles: 
#     - gateway
#     - wordpress

- name: wordpress
  hosts: wordpress
  gather_facts: true
  become: true
  roles: 
    - wordpress

