Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "inetRouter" do |vm|
      vm.vm.network "private_network", adapter: 2, virtualbox__intnet: "router-net",  ip: "10.10.20.254"
      vm.vm.network "private_network", ip: "192.168.50.10", adapter: 5   
      vm.vm.network "forwarded_port", guest: 80, host: 80
      vm.vm.network "forwarded_port", guest: 443, host: 443
      vm.vm.hostname = "inetRouter"
    end


    config.vm.define "wordpress" do |vm|
      vm.vm.network "private_network", adapter: 2, virtualbox__intnet: "router-net",  ip: "10.10.20.10"
      vm.vm.network "private_network", ip: "192.168.50.20", adapter: 5
      vm.vm.network "forwarded_port", guest: 80, host: 8020
      vm.vm.hostname = "wordpress"
    end

    
    config.vm.define "mysql" do |vm|
      vm.vm.network "private_network", adapter: 2, virtualbox__intnet: "router-net",  ip: "10.10.20.20"
      vm.vm.network "private_network", ip: "192.168.50.30", adapter: 5
      vm.vm.hostname = "mysql"
    end
    
    config.vm.define "mysqlslave" do |vm|
      vm.vm.network "private_network", adapter: 2, virtualbox__intnet: "router-net",  ip: "10.10.20.30"
      vm.vm.network "private_network", ip: "192.168.50.40", adapter: 5
      vm.vm.hostname = "mysqlslave"
    end

    config.vm.define "backup" do |vm|
      vm.vm.network "private_network", adapter: 2, virtualbox__intnet: "router-net",  ip: "10.10.20.40"
      vm.vm.network "private_network", ip: "192.168.50.50", adapter: 5
      vm.vm.hostname = "backup"
    end

end

Vagrant.configure("2") do |config|
    config.vm.box = "bento/centos-stream-8"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
  end

  config.vm.define "monitoring" do |vm|
    vm.vm.network "private_network", adapter: 2, virtualbox__intnet: "router-net",  ip: "10.10.20.50"
    vm.vm.network "private_network", ip: "192.168.50.60", adapter: 5
    vm.vm.hostname = "monitoring"
  end

     config.vm.provision "ansible" do |ansible|
     ansible.playbook = "provision.yml"
     ansible.inventory_path = "inventory"
     ansible.config_file = "ansible.cfg"
     ansible.host_key_checking = "false"
     ansible.limit = "all"    
   end 
  

end

