# WordPress database settings
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_host: 10.10.20.20
wp_ip: 10.10.20.10
wp_db_password: '!OtusLinux2018'
  
mysql_port: 3306
mysql_root_password: root

perc_repo: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
mysql_pass: Ctrhtnysqgfhjkm1! #Секретныйпароль1!
mysql_user: root
mysql_db_name: wordpress

#auto_up_disable: true
#webroot: /usr/share/nginx/
server_hostname: wordpress


core_update_level: true