---
# tasks file for monitoring

  - name: install mysql local
    yum:
      name:
        - mysql
        - mysql-server
       # - python
      state: present
    tags: basic

  - name: install mysql_module_py
    dnf:
      name: 
        - python2-PyMySQL
        - python3-PyMySQL
      state: present
    tags: basic

  - name: start services
    service:
      name: mysqld
      state: restarted
      enabled: yes
    tags: basic

  # mysql_secure_installation

  # - name: pwd fix
  #   community.mysql.mysql_user:
  #     login_unix_socket: /var/lib/mysql/mysql.sock
  #     name: root
  #     host: localhost
  #     password: "{{ mysql_password_zab }}"
  #     plugin: mysql_native_password
      
  #   tags: seci, basic, update
  #   ignore_errors: true # 

  - name: Update MariaDB root password
    mysql_user: #community.mysql.mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
    with_items:
      - 127.0.0.1
      - ::1
      - localhost
    ignore_errors: yes
    tags: seci, basic
    #notify: pwd fix


  - name: copy login/pwd
    copy:
      src: "templates/.my.cnf"
      dest: "~/.my.cnf"
    tags: seci, basic
    ignore_errors: true # 

    # mysql_secure_installation
  - name: Delete anonymous MySQL user
    mysql_user: name="" host={{item}} state=absent
    with_items:
      - localhost
      - "{{ansible_nodename}}"
    tags: seci, basic
    ignore_errors: true # 

    # mysql_secure_installation
  - name: Delete Hostname based MySQL user
    mysql_user: name=root host="{{ansible_nodename}}" state=absent
    tags: seci, basic
    ignore_errors: true # 

    # mysql_secure_installation
  - name: Remove MySQL test database
    mysql_db: name=test state=absent
    tags: seci, basic
    ignore_errors: true # 

    #ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
