---
# tasks file for wordpress
  - name: install epel repo
    yum:
      name:
        - epel-release
      state: present
      update_cache: true


  - name: set up forward 
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present


  - name: install soft
    yum:
      name:
        - snapd
        - policycoreutils-python
        - docker
        - docker-compose
        - ca-certificates
        - curl
        - python-cryptography
        # - openssl
        - httpd
        - mlocate
      state: present
      update_cache: true

  - name: start services
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - docker
    #  - snapd
  - name: update locate db
    shell: updatedb


  - name: stop if exist container WORDPRESS, NGINX
    shell:
      cmd: "docker-compose -f docker-compose.yml down || /bin/true"
      chdir: /home/vagrant/
    become: yes
    tags: docker, ssl


  - name: Copy files
    copy: 
      src: "{{ item }}"
      dest: /home/vagrant/
    with_items:
      - docker/docker-compose.yml
      #- .env
      - nginx-conf
    tags: docker

  - name: copy env template
    template:
      src: .env.j2
      dest: /home/vagrant/.env
    tags: docker

  - name: reset ssh connection 
    meta: reset_connection
    tags: docker

  - name: create  nginx dir
    file:
      state: directory
      dest: "{{ item }}"
    with_items:
     - "{{ ssl_path }}"
      

# open ssl
  - name: Create simple self-signed certificate
    openssl_privatekey:
      path:  "{{ ssl_path }}{{ ssl_name }}.pem"
    tags: ssl

  - name: Generate an OpenSSL Certificate Signing Request
    openssl_csr:
      path: "{{ ssl_path }}{{ ssl_name }}.csr"
      privatekey_path:  "{{ ssl_path }}{{ ssl_name }}.pem"
      common_name: "{{ ssl_name }}"
    tags: ssl
    
  - name: Generate a Self Signed OpenSSL certificate
    openssl_certificate:
      path: "{{ ssl_path }}{{ ssl_name }}.crt"
      privatekey_path: "{{ ssl_path }}{{ ssl_name }}.pem"
      csr_path: "{{ ssl_path }}{{ ssl_name }}.csr"
      provider: selfsigned
    tags: ssl



  - name: Run container WORDPRESS, NGINX
    shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: /home/vagrant/
    become: yes
    tags: docker, ssl
