---
# tasks file for wordpress
  - name: install epel repo
    yum:
      name:
        - epel-release
      state: present
      update_cache: true

  - name: install soft
    yum:
      name:
        - nginx
        - snapd
        - policycoreutils-python
        - docker
        - docker-compose
        - ca-certificates
        - curl
        - httpd
      state: present
      update_cache: true

  # - name: Add remote vagrant user to docker
  #   user:
  #     name: vagrant
  #     group: docker
  #     append: yes
  #   tags:
  #     - docker
  - name: start docker
    service:
      name: docker
      enabled: yes
      state: started

  - name: Copy files
    copy: 
      src: "{{ item }}"
      dest: /home/vagrant/
    with_items:
      - docker/docker-compose.yml
      - .env
      - nginx-conf/
    tags: docker
    #force: yes

  - name: reset ssh connection 
    meta: reset_connection
    tags: docker

  - name: Run container
    shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: /home/vagrant/
    become: yes
    tags: docker
