#---
#- hosts: all
#  become: true
#  gather_facts: false
#  vars:
#    mysql_pass: Ctrhtnysqgfhjkm1! #Секретныйпароль1!
#    mysql_user: root
#    mysql_db_name: bet
#  tasks:

#  - name: Ensure MySQL is up-and-running
#    service:
#      name: mysql
#      state: restarted
#      enabled: yes
#    tags: mysql
  
  - name: copy base-conf
    template:
      src: templates/01-base.cnf.j2
      dest: /etc/my.cnf.d/01-base.cnf
      owner: "mysql"
      mode: 0655
      force: yes

  - name: copy login/pwd
    copy:
      src: "templates/.my.cnf"
      dest: "/root/.my.cnf"
      owner: root
    tags: login

  - name: create db
    mysql_db:
      name: "{{ mysql_db_name }}"
      state: present
      login_user: root
      login_unix_socket: "/var/lib/mysql/mysql.sock"
    tags: login

  - name: user otus add
    mysql_user:
      name: "repl"
      password: "!OtusLinux2018"
      state: present
      host: '%'
      login_user: root
      login_unix_socket: "/var/lib/mysql/mysql.sock"
      priv: "*.*:REPLICATION SLAVE"

- hosts: mysql1
  become: true
  gather_facts: false
  vars:
    mysql_pass: Ctrhtnysqgfhjkm1! #Секретныйпароль1!
    mysql_user: root
    mysql_db_name: bet
  tasks:

  - name: copy dump
    copy:
      src: dump.sql
      dest: /tmp/dump.sql

  - name: Restore database
    mysql_db:
      name:  "{{ mysql_db_name }}"
      state: import
      target: "/tmp/dump.sql"
      login_user: root
      login_unix_socket: "/var/lib/mysql/mysql.sock"
    
  - name: dump master db
    mysql_db:
      name: all
      state: dump
      target: /tmp/dump_m.sql
      login_user: root
      login_unix_socket: "/var/lib/mysql/mysql.sock"
      ignore_tables: "bet.events_on_demand,bet.v_same_event"

  - name: copy dump to asnible machine
    fetch:
      src: /tmp/dump_m.sql
      dest: dump_m.sql
      flat: yes

- hosts: mysqlslave
  become: true
  gather_facts: false
  vars:
    mysql_pass: Ctrhtnysqgfhjkm1! #Секретныйпароль1!
    mysql_user: root
    mysql_db_name: "{{ mysql_db_name }}"
    
  tasks:

  - name: enable ssh pwd login
    replace:
      dest: "/etc/ssh/sshd_config"
      regexp: 'PasswordAuthentication no'
      replace: 'PasswordAuthentication yes'
   
  - name: restart sshd
    service:
      name: sshd
      state: restarted
      
  - name: uncomment slave conf
    replace:
      dest: "/etc/my.cnf.d/05-binlog.cnf"
      regexp: '#replicate'
      replace: 'replicate'

  - name: Ensure MySQL is up-and-running
    service:
      name: mysql
      state: restarted
      enabled: yes
    tags: mysql
  
  - name: copy dump
    copy:
      src: dump_m.sql
      dest: /tmp/dump_m.sql

  - name: Restore db from master dump 
    mysql_db:
      name:  "{{ mysql_db_name }}"
      state: import
      target: /tmp/dump_m.sql
      login_user: root
      login_unix_socket: "/var/lib/mysql/mysql.sock"
  
      
      
  - name: config
    mysql_replication:
      mode: changemaster
      master_host: "192.168.50.10"
      master_port: 3306
      master_user: repl
      master_password: "!OtusLinux2018"
      master_auto_position: 1
      login_user: root
      login_unix_socket: "/var/lib/mysql/mysql.sock"
    tags: slave

  - name: start S L A V E
    mysql_replication: 
      mode: startslave
      login_user: root
      login_unix_socket: "/var/lib/mysql/mysql.sock"
    tags: slave

  