
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.define "mysql1" do |mysql|
      mysql.vm.network "private_network", ip: "192.168.50.10"        
      mysql.vm.hostname = "mysql1"
    end

    config.vm.define "mysqlslave" do |mysql|
      mysql.vm.network "private_network",  ip: "192.168.50.11"     
      mysql.vm.hostname = "mysqlslave"      
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.inventory_path = "inventory/hosts"
      ansible.host_key_checking = "false"
      #ansible.limit = "all"
      #ansible.tags = "slave"
      #ansible.verbose = "-vvv"
    end 
  
end


